name: Daily Product Updates

on:
  schedule:
    # প্রতিদিন রাত ১২টায় রান করবে
    - cron: '0 0 * * *'
  # ম্যানুয়ালি রান করার অপশন
  workflow_dispatch:

jobs:
  update-products:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run update script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AMAZON_ACCESS_KEY: ${{ secrets.AMAZON_ACCESS_KEY }}
          AMAZON_SECRET_KEY: ${{ secrets.AMAZON_SECRET_KEY }}
          AMAZON_PARTNER_TAG: ${{ secrets.AMAZON_PARTNER_TAG }}
        run: |
          npm install -g typescript
          npm install -g ts-node
          export NODE_OPTIONS="--loader ts-node/esm --no-warnings"
          npx ts-node --esm scripts/productGenerator.ts
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Daily update $(date +'%Y-%m-%d')" || exit 0
          
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }} 